name: Create-PDF
run-name: ${{ github.actor }} is trying to compile resume
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Get Install Script
        run: wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
      
      - name: Extract tar 
        run: zcat < install-tl-unx.tar.gz | tar xf -

      - name: Remove tar
        run: rm install-tl-unx.tar.gx

      - name: Install texlive
        run: cd install-tl-* && perl install-tl --profile=../texlive.profile

      - name: Update texlive manager
        run:  /home/resume/bin/x86_64-linux/tlmgr update --self

      - name: Install Packages
        run: /home/resume/bin/x86_64-linux/tlmgr install `cat packages.txt`

      - name: Compile
        run: /home/resume/bin/x86_64-linux/pdflatex main.tex

      - name: Commit New PDF
        run: \
          git config --global user.email "arjunsreekumar.1@gmail.com"
          git config --global user.name "Digambaran"
          git add main.pdf
          git commit -m "latest compiled from github action"
          git push


